// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXbsgqs07nR10ziwLVuR18I-Xkw9A1E_E',
    appId: '1:301809525698:web:0b18b7176faa2447abec5b',
    messagingSenderId: '301809525698',
    projectId: 'swcp-app-91b5c',
    authDomain: 'swcp-app-91b5c.firebaseapp.com',
    storageBucket: 'swcp-app-91b5c.firebasestorage.app',
    measurementId: 'G-D73J38JHXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYiPXPtleQ2A-OXX964qrdxh2VzDd1K30',
    appId: '1:301809525698:android:743aefd0f9aa2890abec5b',
    messagingSenderId: '301809525698',
    projectId: 'swcp-app-91b5c',
    storageBucket: 'swcp-app-91b5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXbsgqs07nR10ziwLVuR18I-Xkw9A1E_E',
    appId: '1:301809525698:ios:0b18b7176faa2447abec5b', // Placeholder appId for iOS
    messagingSenderId: '301809525698',
    projectId: 'swcp-app-91b5c',
    storageBucket: 'swcp-app-91b5c.firebasestorage.app',
    iosBundleId: 'com.example.swcpApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXbsgqs07nR10ziwLVuR18I-Xkw9A1E_E',
    appId: '1:301809525698:ios:0b18b7176faa2447abec5b',
    messagingSenderId: '301809525698',
    projectId: 'swcp-app-91b5c',
    storageBucket: 'swcp-app-91b5c.firebasestorage.app',
    iosBundleId: 'com.example.swcpApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXbsgqs07nR10ziwLVuR18I-Xkw9A1E_E',
    appId: '1:301809525698:web:0b18b7176faa2447abec5b',
    messagingSenderId: '301809525698',
    projectId: 'swcp-app-91b5c',
    authDomain: 'swcp-app-91b5c.firebaseapp.com',
    storageBucket: 'swcp-app-91b5c.firebasestorage.app',
    measurementId: 'G-D73J38JHXR',
  );
}
